# Generated by Django 5.0.2 on 2024-02-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='part_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='telegram_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
